:recycle: JWT 키, 시크릿 관리 구조 개선
so-ok/backend pull request #32
Opened 2022-12-27 07:28 UTC by 0chil

2022-12-27 12:36 UTC, clroot requested changes
# "Key" 클래스의 이름을 바꿔야할 것 같음
- "java.security.Key" 클래스와 이름이 겹치는데, jjwt 에서 사용하고 있는 클래스이기에 이 이름은 피할 필요가 있어보임
- "Key" 이름을 피한다면, 기존 Key 클래스에서 java.security.Key 클래스를 사용하는 것으로 Secret 클래스도 없앨 수 있지 않을까
- JWT를 발급하고, 파싱하고, 유효성 체크의 기능을 가지고 있으니 JwtProvider 같은 이름이 더 좋을 것 같음

# "Token" 클래스의 필요성을 잘 모르겠음 > Key 클래스와 기능이 너무 겹침
- token을 String으로 보관하다가, withKey 메서드를 통해 key를 제공받아야만 토큰을 파싱하는 것이 가능해짐
- key 값이 널인지 확인을 하긴 하지만, Token 객체가 key가 함께 있거나, key가 함께 존재하지 않거나 두 가지 상황으로 나뉘는 것 자체가 좋지 않아보임
- 위 "Key" 클래스에서 Secret 객체를 이용해 parser를 생성 후, 파싱하는 메서드가 함께 있는 것이 좋지 않을까 싶음

2022-12-27 13:37 UTC, 0chil reviewed
이름 Key -> TokenProvider로 바꾸고, Secret 및 Token의 역할이 너무 적어 제거하였음.

사실 `Secret`은 parser를 캐싱하고자 하는 목적이 컸는데, 일단 이 PR에서는 하지 않겠음.

2022-12-27 13:44 UTC, 0chil commented
# "Key" 클래스의 이름을 바꿔야할 것 같음
* "java.security.Key" 클래스와 이름이 겹치는데, jjwt 에서 사용하고 있는 클래스이기에 이 이름은 피할 필요가 있어보임
  * OK
* "Key" 이름을 피한다면, 기존 Key 클래스에서 java.security.Key 클래스를 사용하는 것으로 Secret 클래스도 없앨 수 있지 않을까
  * `Secret`이 하는 일이 너무 적어져서 제거하였음.
* JWT를 발급하고, 파싱하고, 유효성 체크의 기능을 가지고 있으니 JwtProvider 같은 이름이 더 좋을 것 같음
  * 마땅한 이름이 없어 결국 JwtProvider로 하였음. 근데 이건 한 클래스가 너무 많은 역할을 가져서 그런 것이라고 생각함.

# "Token" 클래스의 필요성을 잘 모르겠음 > Key 클래스와 기능이 너무 겹침
* token을 String으로 보관하다가, withKey 메서드를 통해 key를 제공받아야만 토큰을 파싱하는 것이 가능해짐
* key 값이 널인지 확인을 하긴 하지만, Token 객체가 key가 함께 있거나, key가 함께 존재하지 않거나 두 가지 상황으로 나뉘는 것 자체가 좋지 않아보임
  * 인정합니다. 모두 걷어냈습니다.
* 위 "Key" 클래스에서 Secret 객체를 이용해 parser를 생성 후, 파싱하는 메서드가 함께 있는 것이 좋지 않을까 싶음
  * OK

사실 jjwt 코드 자체가 별로라서 jjwt 관련된 부분은 이 정도가 거의 최대로 정리한 것으로 보입니다.
또 피드백이 있으면 달아주세요.

2022-12-27 14:06 UTC, clroot approved these changes
- 한결 단순해져 좋음
- TokenProvider::parser 메서드로 parser를 계속 새로 생성해서 사용하는데, JwtParserBuilder::build 에서 immutable/thread-safe 한 객체 반환해줘서, 이거 생성자에서 만들어서 private final로 박아도 ㄱㅊ
- TokenProvider::key 메서드도 동일. immutable 한 객체라서, final로 박아놓아도 문제 없음

2022-12-29 05:10 UTC, 0chil commented
> - 한결 단순해져 좋음
> 
> - TokenProvider::parser 메서드로 parser를 계속 새로 생성해서 사용하는데, JwtParserBuilder::build 에서 immutable/thread-safe 한 객체 반환해줘서, 이거 생성자에서 만들어서 private final로 박아도 ㄱㅊ
> 
> - TokenProvider::key 메서드도 동일. immutable 한 객체라서, final로 박아놓아도 문제 없음
> 
> 

반영 후 머지하겠습니다

2023-01-06 07:38 UTC, merged